apiVersion: v1
kind: ServiceAccount
metadata:
  name: token-refresher
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: token-refresher
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: token-refresher
subjects:
  - kind: ServiceAccount
    name: token-refresher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: token-refresher
